apiVersion: v1
kind: Service
metadata:
  name: {{ include "esi-pod-webhook.fullname" . }}
  namespace: {{ include "esi-pod-webhook.namespace" . }}
  labels:
    {{- include "esi-pod-webhook.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: webhook
      port: {{ .Values.service.webhookPort }}
      targetPort: {{ .Values.service.webhookTargetPort }}
      protocol: TCP
{{- if .Values.debug.enabled }}
    - name: debug
      port: {{ .Values.debug.service.port }}
      targetPort: {{ .Values.debug.service.targetPort }}
      protocol: TCP
{{- end }}
  selector:
    {{- include "esi-pod-webhook.selectorLabels" . | nindent 4 }}
