apiVersion: v2
name: esi-pod-webhook
description: A Helm chart for ESI Pod Webhook, which mutates pods to inject Secretless Broker sidecars or environment variables.
type: application
# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the appVersion.
version: 0.4.6

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the docker image is built with.
appVersion: v0.4.6

keywords:
  - externalsecrets
  - secretless
  - webhook
  - pod
  - mutation